name: TaskFlow CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: windows-latest

    env:
      ConnectionStrings__DefaultConnection: 'Server=(localdb)\MSSQLLocalDB;Database=TaskFlowDb_CI;Trusted_Connection=True;TrustServerCertificate=True;MultipleActiveResultSets=true'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore TaskFlow.sln

      - name: Build solution
        run: dotnet build TaskFlow.sln --configuration Release --no-restore

      - name: Start SQL Server LocalDB
        shell: powershell
        run: |
          sqllocaldb start MSSQLLocalDB

      - name: Install EF Core CLI
        run: dotnet tool install --global dotnet-ef --version 8.0.20

      - name: Apply database migrations
        run: dotnet ef database update --project TaskFlow.Infrastructure --startup-project TaskFlow.API --configuration Release

      - name: Run tests
        run: dotnet test TaskFlow.sln --configuration Release --no-build